language: swift
os: osx
osx_image: xcode12.5
xcode_sdk: iphonesimulator14.5
xcode_project: Machinus.xcodeproj
xcode_scheme: Machinus
language: swift
xcode_destination: platform=iOS Simulator,OS=14.5,name=iPhone 12 Pro
env:
  global:
    - FRAMEWORK_NAME=Machinus
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - carthage bootstrap --no-use-binaries --platform iOS --use-xcframeworks
before_deploy:
  - carthage build --no-skip-current --platform iOS
  - carthage archive $FRAMEWORK_NAME
