language: swift
os: osx
osx_image: xcode11.4
xcode_sdk: iphonesimulator13.4
xcode_project: Machinus.xcodeproj
xcode_scheme: Machinus
language: swift
xcode_destination: platform=iOS Simulator,OS=13.4.1,name=iPhone 11 Pro
env:
  global:
    - FRAMEWORK_NAME=Machinus
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - carthage bootstrap --no-use-binaries
before_deploy:
  - carthage build --no-skip-current  --use-xcframworks
  - carthage archive $FRAMEWORK_NAME
