# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    #- name: Build
    #  run: swift build -v
    - name: Run MacOS tests
      run: swift test # --enable-code-coverage
    - name: Run iOS tests
      run: xcodebuild -scheme Machinus test -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" # --enable-code-coverage
      
    # - name: Convert coverage to lcov
      # run: xcrun llvm-cov export -instr-profile .build/debug/codecov/default.profdata -format="lcov" .build/debug/VoodooPackageTests.xctest/Contents/MacOS/VoodooPackageTests  > coverage.lcov

